# Stage 1: Build Angular app
FROM node:20.11.1-bookworm AS build

# Set the working directory
WORKDIR /usr/src/app

# Copy package.json and package-lock.json files
COPY package*.json ./

# Install dependencies
RUN npm ci

# Copy all files to the container
COPY . .

# Build the Angular app for production
RUN npm run build

# Stage 2: Serve the app with Nginx
FROM nginx:1.27.0-bookworm

# Copy built files from the previous stage to the Nginx web directory
COPY --from=build /usr/src/app/dist/stalta-frontend /usr/share/nginx/html

# Copy custom Nginx configuration file
COPY nginx.conf /etc/nginx/nginx.conf

# Expose port 80
EXPOSE 80

# Start Nginx server
CMD ["nginx", "-g", "daemon off;"]
